import { useState, useRef } from 'react';

const DEFAULT_METRICS = {
  totalSpend: 12400,
  totalRevenue: 43200,
  leads: 287,
  qualified: 134,
  topPlatform: 'TikTok',
  bestROAS: 4.1,
  avgCTR: 1.32,
  newFollowers: 2840,
};

const Section = ({ icon, title, children }) => (
  <div style={{ marginBottom:'1.2rem' }}>
    <div style={{ display:'flex', alignItems:'center', gap:'0.4rem', marginBottom:'0.5rem', borderBottom:'1px solid var(--border)', paddingBottom:'0.3rem' }}>
      <span style={{ fontSize:'0.9rem' }}>{icon}</span>
      <span style={{ fontSize:'0.72rem', fontWeight:800, textTransform:'uppercase', letterSpacing:'0.08em', color:'var(--accent)' }}>{title}</span>
    </div>
    {children}
  </div>
);

const Metric = ({ label, value, sub, highlight }) => (
  <div style={{ display:'inline-flex', flexDirection:'column', background:'var(--card)', border:`1px solid ${highlight?'rgba(0,229,160,0.3)':'var(--border)'}`, borderRadius:'8px', padding:'0.5rem 0.75rem', minWidth:'100px', marginRight:'0.5rem', marginBottom:'0.5rem' }}>
    <span style={{ fontSize:'0.6rem', color:'var(--sub)', textTransform:'uppercase', letterSpacing:'0.07em' }}>{label}</span>
    <span style={{ fontSize:'1.1rem', fontWeight:900, color: highlight ? 'var(--accent)' : 'var(--text)', lineHeight:1.2 }}>{value}</span>
    {sub && <span style={{ fontSize:'0.58rem', color:'var(--sub)', marginTop:'0.1rem' }}>{sub}</span>}
  </div>
);

export default function WeeklyReport({ client, cycleCount, playbook, failures, analyticsText, summaryText, onGenerate }) {
  const [metrics, setMetrics] = useState(DEFAULT_METRICS);
  const [customNotes, setCustomNotes] = useState('');
  const [generating, setGenerating] = useState(false);
  const [reportText, setReportText] = useState('');
  const [reportStream, setReportStream] = useState('');
  const reportRef = useRef(null);

  const roas = (metrics.totalRevenue / metrics.totalSpend).toFixed(2);
  const cpl = (metrics.totalSpend / metrics.leads).toFixed(2);
  const qualRate = ((metrics.qualified / metrics.leads) * 100).toFixed(1);

  const handleMetric = (key, val) => {
    const n = parseFloat(val);
    if (!isNaN(n)) setMetrics(m => ({ ...m, [key]: n }));
  };

  const generateReport = async () => {
    if (!onGenerate) return;
    setGenerating(true);
    setReportStream(''); setReportText('');
    let out = '';
    try {
      await onGenerate({ metrics, roas, cpl, qualRate, customNotes, playbook, failures, cycleCount, analyticsText, summaryText }, c => {
        out = c; setReportStream(c);
      });
      setReportText(out);
    } catch(e) {
      setReportText('⚠ Error generating report: ' + (e.message || 'Unknown error'));
    } finally {
      setGenerating(false);
    }
  };

  const exportMarkdown = () => {
    const text = reportText || buildFallbackReport();
    const blob = new Blob([text], { type: 'text/markdown' });
    const a = Object.assign(document.createElement('a'), {
      href: URL.createObjectURL(blob),
      download: `apexops-weekly-${(client||'client').replace(/\s+/g,'-')}-cycle${cycleCount||0}.md`,
    });
    a.click();
  };

  const buildFallbackReport = () => [
    `# ApexOps Weekly Report — ${client || 'Client'}`,
    `**Period:** Week ending ${new Date().toLocaleDateString()} | **Cycle:** ${cycleCount || 1}`,
    ``,
    `## Performance Summary`,
    `| Metric | Value |`,
    `|---|---|`,
    `| Total Spend | RM ${metrics.totalSpend.toLocaleString()} |`,
    `| Total Revenue | RM ${metrics.totalRevenue.toLocaleString()} |`,
    `| ROAS | ${roas}× |`,
    `| Total Leads | ${metrics.leads} |`,
    `| Qualified Leads | ${metrics.qualified} (${qualRate}%) |`,
    `| Cost / Lead | RM ${cpl} |`,
    `| Best ROAS Campaign | ${metrics.bestROAS}× |`,
    `| Top Platform | ${metrics.topPlatform} |`,
    `| Avg CTR | ${metrics.avgCTR}% |`,
    `| New Followers | +${metrics.newFollowers.toLocaleString()} |`,
    ``,
    `## Playbook (${playbook?.length || 0} entries)`,
    ...(playbook?.map(p => `- ${p}`) || ['- None yet']),
    ``,
    `## Failures Logged (${failures?.length || 0} entries)`,
    ...(failures?.map(f => `- ${f}`) || ['- None yet']),
    ``,
    ...(customNotes ? [`## Notes\n${customNotes}`, ``] : []),
    `---`,
    `*Generated by ApexOps AI — ${new Date().toISOString()}*`,
  ].join('\n');

  const copyMarkdown = () => {
    const text = reportText || buildFallbackReport();
    navigator.clipboard?.writeText(text);
  };

  const editField = (key, label, prefix='', suffix='') => (
    <div style={{ display:'inline-flex', flexDirection:'column', marginRight:'0.5rem', marginBottom:'0.4rem' }}>
      <span style={{ fontSize:'0.58rem', color:'var(--sub)', marginBottom:'0.15rem' }}>{label}</span>
      <div style={{ display:'flex', alignItems:'center', gap:'0.2rem' }}>
        {prefix && <span style={{ fontSize:'0.7rem', color:'var(--sub)' }}>{prefix}</span>}
        <input
          type="number"
          value={metrics[key]}
          onChange={e => handleMetric(key, e.target.value)}
          style={{ width:'80px', background:'var(--dark)', border:'1px solid var(--border)', color:'var(--text)', padding:'0.2rem 0.4rem', borderRadius:'5px', fontSize:'0.72rem', textAlign:'right' }}
        />
        {suffix && <span style={{ fontSize:'0.7rem', color:'var(--sub)' }}>{suffix}</span>}
      </div>
    </div>
  );

  return (
    <div style={{ height:'100%', overflowY:'auto', display:'flex', flexDirection:'column', gap:'0.8rem' }}>

      {/* HEADER */}
      <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', flexWrap:'wrap', gap:'0.5rem' }}>
        <div>
          <div style={{ fontSize:'0.85rem', fontWeight:800, color:'var(--text)' }}>📋 Weekly Performance Report</div>
          <div style={{ fontSize:'0.65rem', color:'var(--sub)', marginTop:'0.1rem' }}>
            {client || 'Client'} · Cycle {cycleCount || 0} · {new Date().toLocaleDateString()}
          </div>
        </div>
        <div style={{ display:'flex', gap:'0.45rem', flexWrap:'wrap' }}>
          <button onClick={copyMarkdown} style={{ background:'var(--card)', border:'1px solid var(--border)', color:'var(--sub)', padding:'0.25rem 0.65rem', borderRadius:'6px', fontSize:'0.68rem', fontWeight:600 }}>📋 Copy MD</button>
          <button onClick={exportMarkdown} style={{ background:'var(--card)', border:'1px solid rgba(0,229,160,0.3)', color:'var(--accent)', padding:'0.25rem 0.65rem', borderRadius:'6px', fontSize:'0.68rem', fontWeight:700 }}>⬇ Export .md</button>
          <button onClick={generateReport} disabled={generating || !onGenerate} style={{ background: generating ? 'var(--muted)' : 'var(--accent)', color: generating ? 'var(--sub)' : 'var(--black)', padding:'0.25rem 0.8rem', borderRadius:'6px', fontSize:'0.72rem', fontWeight:800, opacity: !onGenerate ? 0.5 : 1 }}>
            {generating ? '⟳ Generating…' : '🤖 AI Generate'}
          </button>
        </div>
      </div>

      {/* KPI SNAPSHOT */}
      <Section icon="📊" title="KPI Snapshot">
        <div style={{ display:'flex', flexWrap:'wrap' }}>
          <Metric label="ROAS" value={`${roas}×`} sub={`RM${metrics.totalRevenue.toLocaleString()} / RM${metrics.totalSpend.toLocaleString()}`} highlight={parseFloat(roas) >= 3} />
          <Metric label="Leads" value={metrics.leads} sub={`${metrics.qualified} qualified (${qualRate}%)`} />
          <Metric label="Cost / Lead" value={`RM${cpl}`} sub="total spend ÷ leads" />
          <Metric label="Best ROAS" value={`${metrics.bestROAS}×`} sub={metrics.topPlatform} highlight={metrics.bestROAS >= 3} />
          <Metric label="Avg CTR" value={`${metrics.avgCTR}%`} />
          <Metric label="New Followers" value={`+${metrics.newFollowers.toLocaleString()}`} />
        </div>
      </Section>

      {/* EDITABLE INPUTS */}
      <Section icon="✏️" title="Edit Actuals">
        <div style={{ display:'flex', flexWrap:'wrap', alignItems:'flex-end' }}>
          {editField('totalSpend', 'Total Spend', 'RM')}
          {editField('totalRevenue', 'Total Revenue', 'RM')}
          {editField('leads', 'Total Leads')}
          {editField('qualified', 'Qualified Leads')}
          {editField('bestROAS', 'Best ROAS', '', '×')}
          {editField('avgCTR', 'Avg CTR', '', '%')}
          {editField('newFollowers', 'New Followers', '+')}
        </div>
        <div style={{ marginTop:'0.4rem' }}>
          <span style={{ fontSize:'0.58rem', color:'var(--sub)', display:'block', marginBottom:'0.2rem' }}>Top Platform</span>
          <select
            value={metrics.topPlatform}
            onChange={e => setMetrics(m => ({ ...m, topPlatform: e.target.value }))}
            style={{ background:'var(--dark)', border:'1px solid var(--border)', color:'var(--text)', padding:'0.22rem 0.5rem', borderRadius:'5px', fontSize:'0.72rem' }}
          >
            {['TikTok','Instagram','YouTube','X'].map(p => <option key={p}>{p}</option>)}
          </select>
        </div>
      </Section>

      {/* AGENT MEMORY SUMMARY */}
      <Section icon="🧠" title={`Agent Memory · ${playbook?.length||0} Playbook · ${failures?.length||0} Failures`}>
        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:'0.5rem' }}>
          <div>
            <div style={{ fontSize:'0.6rem', fontWeight:700, color:'var(--accent)', marginBottom:'0.3rem' }}>PLAYBOOK — What Works</div>
            {(!playbook || playbook.length === 0)
              ? <div style={{ fontSize:'0.65rem', color:'var(--sub)', fontStyle:'italic' }}>No learnings yet — run a cycle.</div>
              : playbook.slice(-5).map((p, i) => (
                <div key={i} style={{ fontSize:'0.63rem', color:'var(--text)', padding:'0.2rem 0', borderBottom:'1px solid rgba(255,255,255,0.05)' }}>• {p}</div>
              ))
            }
          </div>
          <div>
            <div style={{ fontSize:'0.6rem', fontWeight:700, color:'var(--warn)', marginBottom:'0.3rem' }}>FAILURES — Never Repeat</div>
            {(!failures || failures.length === 0)
              ? <div style={{ fontSize:'0.65rem', color:'var(--sub)', fontStyle:'italic' }}>No failures logged.</div>
              : failures.slice(-5).map((f, i) => (
                <div key={i} style={{ fontSize:'0.63rem', color:'var(--text)', padding:'0.2rem 0', borderBottom:'1px solid rgba(255,255,255,0.05)' }}>✗ {f}</div>
              ))
            }
          </div>
        </div>
      </Section>

      {/* ADDITIONAL NOTES */}
      <Section icon="📝" title="Additional Notes">
        <textarea
          value={customNotes}
          onChange={e => setCustomNotes(e.target.value)}
          placeholder="Add context, observations, or client notes for the report…"
          rows={3}
          style={{ width:'100%', background:'var(--dark)', border:'1px solid var(--border)', color:'var(--text)', padding:'0.4rem 0.6rem', borderRadius:'6px', fontSize:'0.72rem', resize:'vertical', fontFamily:'inherit', boxSizing:'border-box' }}
        />
      </Section>

      {/* AI-GENERATED REPORT OUTPUT */}
      {(reportText || reportStream) && (
        <Section icon="🤖" title="AI-Generated Report">
          <div ref={reportRef} style={{ background:'var(--dark)', border:'1px solid var(--border)', borderRadius:'8px', padding:'0.75rem', maxHeight:'360px', overflowY:'auto' }}>
            <pre style={{ whiteSpace:'pre-wrap', wordBreak:'break-word', fontSize:'0.72rem', color:'var(--text)', lineHeight:1.75, fontFamily:'inherit', margin:0 }}>
              {reportText || reportStream}
              {generating && !reportText && <span style={{ color:'var(--accent)' }}>▊</span>}
            </pre>
          </div>
        </Section>
      )}

      {/* FALLBACK STATIC PREVIEW */}
      {!reportText && !reportStream && (
        <Section icon="👁" title="Report Preview (static — click AI Generate for full version)">
          <div style={{ background:'var(--dark)', border:'1px solid var(--border)', borderRadius:'8px', padding:'0.75rem', maxHeight:'280px', overflowY:'auto' }}>
            <pre style={{ whiteSpace:'pre-wrap', wordBreak:'break-word', fontSize:'0.68rem', color:'var(--sub)', lineHeight:1.75, fontFamily:'inherit', margin:0 }}>
              {buildFallbackReport()}
            </pre>
          </div>
        </Section>
      )}

    </div>
  );
}
